ServerConfig:
  AppVersion: 1.0.0
  Mode: Development
  RoutePrefix: /api/v1/shopping-basket-api
  Debug: false
  Port: 8080
  TimeoutSecs: 60
  ReadTimeoutSecs: 60
  WriteTimeoutSecs: 12
  ShutdownTimeoutSecs: 15

JWTConfig:
  SessionTime: 3600
  SecretKey: authorizationKey
  SecretKetRefresh: refreshAuthorizationKey
  AccessTokenDurationMins: 15
  RefreshTokenDurationHours: 168

DBConfig:
  DataSourceName: user=postgres dbname=shopping-basket-app password=Gopher822 host=localhost sslmode=disable
  Name: shopping-basket-app
  MaxOpen: 50
  MaxIdle: 50
  MaxLifetime: 5
  MigrationFolder: file://migrations

Logger:
  Development: true
  Encoding: json
  Level: info
